[package]
name = "sr_02_line"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.26.0"
tobj = "4.0.2"
fastnoise-lite = "1.1.1"
rand = "0.8.5"
